# version: 1

project_name: beszel

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    main: cmd/hub/hub.go

  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - mips64
    ignore:
      - goos: freebsd
        goarch: arm
    main: cmd/agent/agent.go

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    # use zip for windows archives
    # format_overrides:
    #   - goos: windows
    #     format: zip

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
