# version: 1

project_name: beszel-agent

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - mips64
    ignore:
      - goos: freebsd
        goarch: arm

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
