services:
  beszel-agent:
    image: 'henrygd/beszel-agent'
    container_name: 'beszel-agent'
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FILESYSTEM=/dev/sda1 # Set to the correct filesystem for disk I/O stats
      - KEY="ssh-ed25519 YOUR_PUBLIC_KEY"
