# version: 1

project_name: beszel

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: 386

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
